apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookshelf-service
  template:
    metadata:
      labels:
        app: bookshelf-service
    spec:
      containers:
        - name: bookshelf-service
          image: cikacira/bookshelf-service:latest
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: bookshelf-service
spec:
  selector:
    app: bookshelf-service
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8082
      nodePort: 30002

